2025-02-20 03:23:43,355 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.91.58.84:5000
2025-02-20 03:23:43,356 - INFO - [33mPress CTRL+C to quit[0m
2025-02-20 03:23:54,717 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\PycharmProjects\devops\S25-core-course-labs\app_python\app\app.py", line 31, in index
    logging.info(f"Served current time: {current_time}")
                                         ^^^^^^^^^^^^
NameError: name 'current_time' is not defined
2025-02-20 03:23:54,751 - INFO - 127.0.0.1 - - [20/Feb/2025 03:23:54] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-02-20 03:24:21,541 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\PycharmProjects\devops\S25-core-course-labs\app_python\app\app.py", line 31, in index
    logging.info(f"Served current time: {current_time}")
                                         ^^^^^^^^^^^^
NameError: name 'current_time' is not defined
2025-02-20 03:24:21,552 - INFO - 127.0.0.1 - - [20/Feb/2025 03:24:21] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-02-20 03:24:23,855 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User_MAA\PycharmProjects\devops\S25-core-course-labs\app_python\app\app.py", line 31, in index
    logging.info(f"Served current time: {current_time}")
                                         ^^^^^^^^^^^^
NameError: name 'current_time' is not defined
2025-02-20 03:24:23,866 - INFO - 127.0.0.1 - - [20/Feb/2025 03:24:23] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-02-20 03:24:24,172 - INFO - 127.0.0.1 - - [20/Feb/2025 03:24:24] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
